export interface FileEntry {
  path: string;
  type: 'file' | 'dir';
  purpose: string;
  exports?: string[];
  dbTables?: string[];
  apiCalls?: string[];
  children?: FileEntry[];
}

export const FILE_TREE: FileEntry[] = [
  {
    path: 'src/',
    type: 'dir',
    purpose: 'Application source root — contains all Astra Control Plane code: Next.js pages, API routes, components, shared libraries, AI providers, and the full scan pipeline engine. The Control Plane is stateful (PostgreSQL via Prisma) and orchestrates the Data Plane which runs scanners in an isolated container.',
    children: [
      {
        path: 'src/middleware.ts',
        type: 'file',
        purpose: 'Auth middleware wrapping all routes with NextAuth auth(). Public routes: /, /auth/*, /api/auth/*, /api/v1/auth/*, /api/v1/health, /_next/*, /favicon.ico. All others redirect to /auth/signin if unauthenticated.',
        exports: ['default (auth middleware)'],
      },
      {
        path: 'src/instrumentation.ts',
        type: 'file',
        purpose: 'Next.js instrumentation hook — initializes structured logger on startup.',
        exports: ['register'],
      },
      {
        path: 'src/types/',
        type: 'dir',
        purpose: 'TypeScript type augmentation declarations — extends third-party module types (NextAuth Session/User) with Astra-specific fields like id and role.',
        children: [
          { path: 'src/types/next-auth.d.ts', type: 'file', purpose: 'Extends NextAuth Session and User types with id and role fields.' },
        ],
      },
      {
        path: 'src/app/',
        type: 'dir',
        purpose: 'Next.js App Router — all pages and API routes. Uses directory-based routing: page.tsx files define routes, layout.tsx files wrap child routes, and route.ts files define API endpoints. Organized into authenticated (app) group with AppShell nav and public auth pages.',
        children: [
          { path: 'src/app/page.tsx', type: 'file', purpose: 'Landing page. Redirects authenticated users to /scans.' },
          { path: 'src/app/layout.tsx', type: 'file', purpose: 'Root layout wrapping all pages with ThemeProvider, AuthProvider, TooltipProvider, and Toaster.' },
          {
            path: 'src/app/(app)/',
            type: 'dir',
            purpose: 'Authenticated app group — all pages in this route group require login (enforced by middleware). Shares the AppShell layout with top nav, utility bar, user menu, and slide-out AI chat panel. Contains the main functional pages: Scans dashboard, scan detail with 7 tabs, task management, config editor, observability, pipeline editor, rules, glossary, and changelog.',
            children: [
              { path: 'src/app/(app)/layout.tsx', type: 'file', purpose: 'App shell layout wrapping all authenticated pages with AppShell navigation.' },
              { path: 'src/app/(app)/scans/page.tsx', type: 'file', purpose: 'Main dashboard — create scans, view recent scans with severity badges.', apiCalls: ['GET /api/v1/scans'] },
              { path: 'src/app/(app)/scans/[id]/page.tsx', type: 'file', purpose: 'Scan detail with 7 tabs: Overview, Alerts, Files, Rules, Pipeline, Chat, AI Calls.', apiCalls: ['GET /api/v1/scans/{id}', 'POST /api/v1/scans/{id}/resume', 'POST /api/v1/scans/{id}/cancel', 'POST /api/v1/scans'] },
              { path: 'src/app/(app)/scans/[id]/report/page.tsx', type: 'file', purpose: 'Standalone scan report with executive summary, file browser, and finding detail.' },
              { path: 'src/app/(app)/scans/[id]/nodes/[node]/page.tsx', type: 'file', purpose: 'Single pipeline node drill-down (config, I/O JSON, tokens, timing).', apiCalls: ['GET /api/v1/scans/{id}/nodes'] },
              { path: 'src/app/(app)/tasks/page.tsx', type: 'file', purpose: 'Task management dashboard with data table.', apiCalls: ['GET /api/v1/tasks'] },
              { path: 'src/app/(app)/config/page.tsx', type: 'file', purpose: 'Configuration editor page (renders ConfigEditor component).' },
              { path: 'src/app/(app)/observability/page.tsx', type: 'file', purpose: 'AI call observability dashboard.', apiCalls: ['GET /api/v1/ai-calls/stats'] },
              { path: 'src/app/(app)/pipeline/page.tsx', type: 'file', purpose: 'Visual pipeline config editor with per-node settings.', apiCalls: ['GET /api/v1/config', 'PUT /api/v1/config'] },
              { path: 'src/app/(app)/changelog/page.tsx', type: 'file', purpose: 'Release history page (this page).' },
              { path: 'src/app/(app)/rules/page.tsx', type: 'file', purpose: 'Two-tab rules page: Global Rules (CRUD) and AI-Inferred Rules (confirm/reject).', apiCalls: ['GET/POST/PATCH/DELETE /api/v1/user-rules', 'GET/PATCH /api/v1/rules'] },
              { path: 'src/app/(app)/settings/page.tsx', type: 'file', purpose: 'Settings hub with links to Profile, GitHub, and User Management.' },
              { path: 'src/app/(app)/settings/github/page.tsx', type: 'file', purpose: 'GitHub integration settings (server component + client).', dbTables: ['GithubProfile'] },
              { path: 'src/app/(app)/settings/profile/page.tsx', type: 'file', purpose: 'Profile settings page.', apiCalls: ['GET /api/v1/auth/me'] },
              { path: 'src/app/(app)/settings/users/page.tsx', type: 'file', purpose: 'Admin user management: list, create, change roles, delete.', apiCalls: ['GET /api/v1/users', 'POST /api/v1/auth/signup', 'PATCH/DELETE /api/v1/users/{id}'] },
            ],
          },
          {
            path: 'src/app/auth/',
            type: 'dir',
            purpose: 'Public authentication pages — sign-in and sign-up forms. These routes are accessible without login (middleware whitelists /auth/*). Uses NextAuth v5 (AuthJS) credentials provider with bcrypt password hashing and JWT session strategy.',
            children: [
              { path: 'src/app/auth/signin/page.tsx', type: 'file', purpose: 'Email/password sign-in form.' },
              { path: 'src/app/auth/signup/page.tsx', type: 'file', purpose: 'Account registration page.', apiCalls: ['POST /api/v1/auth/signup'] },
            ],
          },
          {
            path: 'src/app/api/v1/',
            type: 'dir',
            purpose: 'REST API v1 routes — all endpoints require authentication (requireAuth) unless explicitly public. Organized by resource: auth (login/signup/me), scans (CRUD + pipeline control), findings (CRUD + chat/comments/history), tasks (CRUD + AI suggestions), ai-calls (observability + retry), chat (global AI), config (scan config), providers (AI registry), prompts (system prompt management), rules (AI-inferred business logic), user-rules (custom rules), users (admin management), github (OAuth integration).',
            children: [
              { path: 'src/app/api/auth/[...nextauth]/route.ts', type: 'file', purpose: 'NextAuth catch-all handler for all auth routes (sign-in, sign-out, callbacks).' },
              { path: 'src/app/api/v1/auth/me/route.ts', type: 'file', purpose: 'Get current user profile + GitHub info.', dbTables: ['User', 'GithubProfile'] },
              { path: 'src/app/api/v1/auth/signup/route.ts', type: 'file', purpose: 'Register new user account. Rate-limited 5/min per IP.', dbTables: ['User'] },
              { path: 'src/app/api/v1/auth/verify/route.ts', type: 'file', purpose: 'Verify email/password credentials. Rate-limited 10/min per IP.', dbTables: ['User'] },
              { path: 'src/app/api/v1/health/route.ts', type: 'file', purpose: 'DB health check (SELECT 1). Public, no auth.' },
              { path: 'src/app/api/v1/scans/route.ts', type: 'file', purpose: 'List scans / Create new scan.', dbTables: ['Scan', 'UserRule'], exports: ['GET', 'POST'] },
              { path: 'src/app/api/v1/scans/[id]/route.ts', type: 'file', purpose: 'Get scan detail with findings, rules, node outputs.', dbTables: ['Scan', 'Finding', 'BusinessLogicRule', 'NodeOutput'] },
              { path: 'src/app/api/v1/scans/[id]/cancel/route.ts', type: 'file', purpose: 'Cancel running scan.', dbTables: ['Job', 'Scan'] },
              { path: 'src/app/api/v1/scans/[id]/chat/route.ts', type: 'file', purpose: 'Scan-level AI chat (GET history + POST message).', dbTables: ['AiConversation', 'Scan', 'Finding'] },
              { path: 'src/app/api/v1/scans/[id]/export/route.ts', type: 'file', purpose: 'Export scan results (JSON/CSV/Markdown/HTML/SARIF).' },
              { path: 'src/app/api/v1/scans/[id]/logs/route.ts', type: 'file', purpose: 'Paginated scan logs.', dbTables: ['ScanLog'] },
              { path: 'src/app/api/v1/scans/[id]/nodes/route.ts', type: 'file', purpose: 'Get pipeline node outputs.', dbTables: ['NodeOutput'] },
              { path: 'src/app/api/v1/scans/[id]/progress/route.ts', type: 'file', purpose: 'Real-time pipeline progress.', dbTables: ['Scan', 'ScanLog'] },
              { path: 'src/app/api/v1/scans/[id]/rerun-node/route.ts', type: 'file', purpose: 'Re-run a single pipeline node.', dbTables: ['Job', 'Finding', 'Scan'] },
              { path: 'src/app/api/v1/scans/[id]/resume/route.ts', type: 'file', purpose: 'Resume a failed scan.', dbTables: ['Job', 'Scan'] },
              { path: 'src/app/api/v1/scans/[id]/stream/route.ts', type: 'file', purpose: 'SSE endpoint streaming real-time scan updates.', dbTables: ['Scan', 'Job'] },
              { path: 'src/app/api/v1/findings/route.ts', type: 'file', purpose: 'List findings with extensive filtering.', dbTables: ['Finding'] },
              { path: 'src/app/api/v1/findings/[id]/route.ts', type: 'file', purpose: 'Get/update a single finding (status, assignment).', dbTables: ['Finding', 'AlertHistory'] },
              { path: 'src/app/api/v1/findings/[id]/chat/route.ts', type: 'file', purpose: 'Finding-level AI chat with full finding context.', dbTables: ['AiConversation', 'Finding'] },
              { path: 'src/app/api/v1/findings/[id]/comments/route.ts', type: 'file', purpose: 'List/add comments on a finding.', dbTables: ['AlertComment', 'AlertHistory'] },
              { path: 'src/app/api/v1/findings/[id]/history/route.ts', type: 'file', purpose: 'Finding audit history.', dbTables: ['AlertHistory'] },
              { path: 'src/app/api/v1/findings/[id]/rescan/route.ts', type: 'file', purpose: 'Per-file rescan — re-runs deep_scan on one file.', dbTables: ['Finding', 'Scan', 'Job'] },
              { path: 'src/app/api/v1/findings/[id]/task/route.ts', type: 'file', purpose: 'Create a FINDING_TRIAGE task from a finding.', dbTables: ['Finding', 'Task'] },
              { path: 'src/app/api/v1/tasks/route.ts', type: 'file', purpose: 'List/create tasks.', dbTables: ['Task', 'TaskHistory'] },
              { path: 'src/app/api/v1/tasks/[id]/route.ts', type: 'file', purpose: 'Get/update/delete a task.', dbTables: ['Task', 'TaskHistory'] },
              { path: 'src/app/api/v1/tasks/[id]/comments/route.ts', type: 'file', purpose: 'List/add comments on a task.', dbTables: ['TaskComment', 'TaskHistory'] },
              { path: 'src/app/api/v1/tasks/[id]/history/route.ts', type: 'file', purpose: 'Task audit history.', dbTables: ['TaskHistory'] },
              { path: 'src/app/api/v1/tasks/[id]/rescan/route.ts', type: 'file', purpose: 'Rescan the file linked to a task.', dbTables: ['Task', 'Finding', 'Scan', 'Job'] },
              { path: 'src/app/api/v1/tasks/ai-suggest/route.ts', type: 'file', purpose: 'AI-powered task grouping suggestions.', dbTables: ['Finding'] },
              { path: 'src/app/api/v1/tasks/batch/route.ts', type: 'file', purpose: 'Batch task operations (reassign, status, delete).', dbTables: ['Task', 'TaskHistory'] },
              { path: 'src/app/api/v1/ai-calls/route.ts', type: 'file', purpose: 'List AI call logs with filtering.', dbTables: ['AiCallLog'] },
              { path: 'src/app/api/v1/ai-calls/[id]/route.ts', type: 'file', purpose: 'Get single AI call detail.', dbTables: ['AiCallLog'] },
              { path: 'src/app/api/v1/ai-calls/[id]/retry/route.ts', type: 'file', purpose: 'Re-execute a logged AI call.', dbTables: ['AiCallLog'] },
              { path: 'src/app/api/v1/ai-calls/stats/route.ts', type: 'file', purpose: 'Aggregate AI call statistics.', dbTables: ['AiCallLog'] },
              { path: 'src/app/api/v1/chat/route.ts', type: 'file', purpose: 'Global AI chat (not tied to scan/finding).', dbTables: ['AiConversation'] },
              { path: 'src/app/api/v1/config/route.ts', type: 'file', purpose: 'Get/update global scan config (admin-only).', dbTables: ['Config'] },
              { path: 'src/app/api/v1/providers/route.ts', type: 'file', purpose: 'List available AI providers and models.' },
              { path: 'src/app/api/v1/providers/test/route.ts', type: 'file', purpose: 'Test AI provider connectivity.' },
              { path: 'src/app/api/v1/presets/route.ts', type: 'file', purpose: 'List/create scan config presets.', dbTables: ['Preset'] },
              { path: 'src/app/api/v1/preferences/route.ts', type: 'file', purpose: 'Get/set user preferences.', dbTables: ['UserPreference'] },
              { path: 'src/app/api/v1/prompts/route.ts', type: 'file', purpose: 'Get/edit/reset system prompts (admin-only mutations).', dbTables: ['Config'] },
              { path: 'src/app/api/v1/rules/route.ts', type: 'file', purpose: 'List AI-inferred business logic rules.', dbTables: ['BusinessLogicRule'] },
              { path: 'src/app/api/v1/rules/[id]/route.ts', type: 'file', purpose: 'Update rule status (CANDIDATE/CONFIRMED/REJECTED).', dbTables: ['BusinessLogicRule'] },
              { path: 'src/app/api/v1/user-rules/route.ts', type: 'file', purpose: 'List/create user-defined custom rules.', dbTables: ['UserRule'] },
              { path: 'src/app/api/v1/user-rules/[id]/route.ts', type: 'file', purpose: 'Update/delete a custom rule.', dbTables: ['UserRule'] },
              { path: 'src/app/api/v1/users/route.ts', type: 'file', purpose: 'List all users (admin-only).', dbTables: ['User'] },
              { path: 'src/app/api/v1/users/[id]/route.ts', type: 'file', purpose: 'Change role or delete user (admin-only).', dbTables: ['User'] },
              { path: 'src/app/api/v1/github/branches/route.ts', type: 'file', purpose: 'List branches for a GitHub repo.', dbTables: ['GithubProfile'] },
              { path: 'src/app/api/v1/github/link/route.ts', type: 'file', purpose: 'Link GitHub account via PAT.', dbTables: ['GithubProfile'] },
              { path: 'src/app/api/v1/github/repos/route.ts', type: 'file', purpose: 'List user\'s accessible GitHub repos.', dbTables: ['GithubProfile'] },
              { path: 'src/app/api/v1/github/unlink/route.ts', type: 'file', purpose: 'Remove GitHub profile.', dbTables: ['GithubProfile'] },
            ],
          },
        ],
      },
      {
        path: 'src/components/',
        type: 'dir',
        purpose: 'React UI components — the entire presentation layer. Built with inline styles following IBM Carbon Design System (0px border radius, IBM Plex Sans, surface hierarchy). Key components: AppShell (global nav + chat), RepoInput (scan launcher), FilterableFindingsTable + AlertDetail (finding management), ConfigEditor (scan config + prompts), AiChatProvider (slide-out chat), TaskDataTable (task CRUD + AI suggestions), ScanProgress (6-node pipeline viewer).',
        children: [
          { path: 'src/components/AppShell.tsx', type: 'file', purpose: 'Top-level layout with nav, user menu, chat FAB.', exports: ['default (AppShell)'] },
          { path: 'src/components/AuthProvider.tsx', type: 'file', purpose: 'Wraps next-auth SessionProvider.' },
          { path: 'src/components/ThemeProvider.tsx', type: 'file', purpose: 'Light/dark theme context + persistence.', apiCalls: ['GET/POST /api/v1/preferences'] },
          { path: 'src/components/ThemeToggle.tsx', type: 'file', purpose: 'Light/dark toggle button.' },
          { path: 'src/components/UserButton.tsx', type: 'file', purpose: 'User dropdown with settings + sign out.' },
          { path: 'src/components/RepoInput.tsx', type: 'file', purpose: 'Scan launch form with GitHub browser, branch picker, presets, rules.', apiCalls: ['GET repos', 'GET branches', 'POST scans'] },
          { path: 'src/components/ScanProgress.tsx', type: 'file', purpose: 'Real-time 6-node pipeline progress viewer.', apiCalls: ['GET /api/v1/scans/{id}/progress'] },
          { path: 'src/components/ScanChat.tsx', type: 'file', purpose: 'Inline per-scan AI chat widget.', apiCalls: ['GET/POST /api/v1/scans/{id}/chat'] },
          { path: 'src/components/DashboardMetrics.tsx', type: 'file', purpose: 'Summary metric cards + severity/category bars.' },
          { path: 'src/components/ScannerBreakdown.tsx', type: 'file', purpose: 'Finding counts by severity & scanner.' },
          { path: 'src/components/ExportPanel.tsx', type: 'file', purpose: 'Export buttons (JSON/CSV/SARIF/HTML/Markdown).', apiCalls: ['GET /api/v1/scans/{id}/export'] },
          { path: 'src/components/SeverityBadge.tsx', type: 'file', purpose: 'Color-coded severity tag.' },
          { path: 'src/components/FilterableFindingsTable.tsx', type: 'file', purpose: 'Full-featured filterable/sortable findings table with detail panel.' },
          { path: 'src/components/FindingsTable.tsx', type: 'file', purpose: 'Simpler expandable findings table.' },
          { path: 'src/components/AlertDetail.tsx', type: 'file', purpose: 'Slide-in finding detail: status, comments, AI chat, rescan, task creation.', apiCalls: ['GET/PATCH /api/v1/findings/{id}', 'POST comments/task/rescan'] },
          { path: 'src/components/FileExplorer.tsx', type: 'file', purpose: 'Filterable file tree with findings grouped by path.' },
          { path: 'src/components/BusinessLogicPanel.tsx', type: 'file', purpose: 'Inferred rules with confirm/reject actions.', apiCalls: ['PATCH /api/v1/rules/{id}'] },
          { path: 'src/components/TaskDataTable.tsx', type: 'file', purpose: 'Task management table with filters, batch ops, AI suggestions, comments, history, rescan.' },
          { path: 'src/components/ConfigEditor.tsx', type: 'file', purpose: 'Tabbed scan config editor (nodes + chat + prompts).', apiCalls: ['GET/PUT /api/v1/config', 'GET /api/v1/providers', 'GET/PUT/DELETE /api/v1/prompts'] },
          { path: 'src/components/PresetSelector.tsx', type: 'file', purpose: 'Preset dropdown.', apiCalls: ['GET /api/v1/presets'] },
          { path: 'src/components/ProviderSelector.tsx', type: 'file', purpose: 'Provider/model selector with test connection.', apiCalls: ['GET /api/v1/providers', 'POST /api/v1/providers/test'] },
          { path: 'src/components/ThinkingControls.tsx', type: 'file', purpose: 'Thinking depth radio + budget slider.' },
          { path: 'src/components/AiCallTable.tsx', type: 'file', purpose: 'Paginated AI call log table with retry.', apiCalls: ['GET /api/v1/ai-calls', 'GET /api/v1/ai-calls/stats', 'POST /api/v1/ai-calls/{id}/retry'] },
          { path: 'src/components/NodeOutputInspector.tsx', type: 'file', purpose: 'Pipeline node output viewer with rerun.', apiCalls: ['POST /api/v1/scans/{id}/rerun-node'] },
          { path: 'src/components/LiveLog.tsx', type: 'file', purpose: 'Polling live-log viewer.', apiCalls: ['GET /api/v1/scans/{id}/logs'] },
          { path: 'src/components/AiChatProvider.tsx', type: 'file', purpose: 'Global slide-out chat panel.', apiCalls: ['GET/POST /api/v1/chat', 'GET/POST /api/v1/findings/{id}/chat'] },
          { path: 'src/components/GitHubLinkPrompt.tsx', type: 'file', purpose: 'GitHub PAT link form.', apiCalls: ['POST /api/v1/github/link'] },
        ],
      },
      {
        path: 'src/lib/',
        type: 'dir',
        purpose: 'Shared libraries — the backbone of the Control Plane. Contains auth (NextAuth v5 config, RBAC helpers), config (Zod schemas + DB-backed load/save with prompt management), AI chat orchestration (provider resolution + multi-turn history), instrumentation (observability wrapping every AI call), encryption (AES-256-GCM for GitHub tokens), GitHub API client, pagination, rate limiting, task-findings sync, token estimation, and structured logging.',
        children: [
          { path: 'src/lib/auth.ts', type: 'file', purpose: 'NextAuth v5 config (credentials, JWT, callbacks).', exports: ['handlers', 'auth', 'signIn', 'signOut'] },
          { path: 'src/lib/config.ts', type: 'file', purpose: 'Zod config schemas, DB loader/saver, node overrides, prompt DB helpers.', exports: ['configSchema', 'AstraConfig', 'NodeConfig', 'ChatConfig', 'loadConfig', 'loadConfigFromDb', 'saveConfigToDb', 'mergeNodeOverrides', 'loadPromptFromDb', 'savePromptToDb', 'listPromptsFromDb'], dbTables: ['Config'] },
          { path: 'src/lib/db.ts', type: 'file', purpose: 'Singleton PrismaClient with PrismaPg adapter.', exports: ['prisma'] },
          { path: 'src/lib/ai-chat.ts', type: 'file', purpose: 'Chat orchestration — resolves provider, loads DB prompts, builds system prompt with context + conversation history.', exports: ['sendChatMessage'] },
          { path: 'src/lib/ai-instrumentation.ts', type: 'file', purpose: 'Wraps AI calls with observability — logs to AiCallLog.', exports: ['InstrumentationSource', 'InstrumentationContext', 'instrumentedSend'], dbTables: ['AiCallLog'] },
          { path: 'src/lib/rbac.ts', type: 'file', purpose: 'Auth helpers — requireAuth, role checks, scan ownership.', exports: ['requireAuth', 'requireRole', 'canWrite', 'canAdmin', 'requireScanOwnership'] },
          { path: 'src/lib/encryption.ts', type: 'file', purpose: 'AES-256-GCM encrypt/decrypt with enc: prefix backward compat.', exports: ['encrypt', 'decrypt'] },
          { path: 'src/lib/github.ts', type: 'file', purpose: 'GitHub REST API client for repos + branches.', exports: ['getGithubRepos', 'getGithubBranches'] },
          { path: 'src/lib/pagination.ts', type: 'file', purpose: 'Parse/validate limit/offset query params.', exports: ['PaginationParams', 'parsePagination'] },
          { path: 'src/lib/rate-limit.ts', type: 'file', purpose: 'In-memory sliding-window rate limiter.', exports: ['rateLimit'] },
          { path: 'src/lib/task-sync.ts', type: 'file', purpose: 'Create triage tasks from findings + bidirectional assignment sync.', exports: ['createTaskFromFinding', 'syncFindingAssignmentToTask', 'syncTaskAssignmentToFinding'], dbTables: ['Finding', 'Task'] },
          { path: 'src/lib/tokenizer.ts', type: 'file', purpose: 'Character-based token estimator + available token calculator.', exports: ['estimateTokens', 'calculateAvailableTokens'] },
          { path: 'src/lib/logger.ts', type: 'file', purpose: 'Console logger with levels, colors, progress bar.', exports: ['LogLevel', 'setLogLevel', 'step', 'info', 'success', 'warn', 'error'] },
          { path: 'src/lib/structured-logger.ts', type: 'file', purpose: 'Edge-safe logger facade (re-exports Pino on Node.js, silent on Edge).', exports: ['logger', 'Logger'] },
          { path: 'src/lib/structured-logger-node.ts', type: 'file', purpose: 'Pino JSON logger writing to logs/ directory.', exports: ['logger'] },
          { path: 'src/lib/changelog.ts', type: 'file', purpose: 'Static changelog data array.', exports: ['ChangelogEntry', 'CHANGELOG'] },
          { path: 'src/lib/utils.ts', type: 'file', purpose: 'Tailwind class merge utility (shadcn convention).', exports: ['cn'] },
          { path: 'src/lib/file-tree.ts', type: 'file', purpose: 'File tree data for the glossary page.', exports: ['FileEntry', 'FILE_TREE'] },
        ],
      },
      {
        path: 'src/providers/',
        type: 'dir',
        purpose: 'AI provider implementations — 7 providers implement the AIProvider interface (send, sendStream, testConnection, estimateTokens). Active providers: cloud-ollama, hosted-ollama, openai, anthropic. Stub providers: bedrock, azure-ai-foundry, langgraph-connector. Factory pattern resolves provider by config; registry lists available models for the UI.',
        children: [
          { path: 'src/providers/base.ts', type: 'file', purpose: 'Provider contract — AIProvider interface, request/response types, multi-turn ChatMessage.', exports: ['AIProvider', 'AIRequest', 'AIResponse', 'ChatMessage', 'ModelInfo', 'ThinkingDepth', 'ScanDepth'] },
          { path: 'src/providers/factory.ts', type: 'file', purpose: 'Instantiate provider by ID + config; helper for node-scoped providers.', exports: ['createProvider', 'createProviderForNode'] },
          { path: 'src/providers/registry.ts', type: 'file', purpose: 'List configured providers & models for UI.', exports: ['listProviders'] },
          { path: 'src/providers/cloud-ollama.ts', type: 'file', purpose: 'Cloud Ollama provider with retry + empty-response detection. Uses chat() for multi-turn.', exports: ['CloudOllamaProvider'] },
          { path: 'src/providers/hosted-ollama.ts', type: 'file', purpose: 'Self-hosted Ollama with empty-response detection. Uses chat() for multi-turn.', exports: ['HostedOllamaProvider'] },
          { path: 'src/providers/openai.ts', type: 'file', purpose: 'OpenAI Chat Completions provider.', exports: ['OpenAIProvider'] },
          { path: 'src/providers/anthropic.ts', type: 'file', purpose: 'Anthropic Messages provider with extended thinking.', exports: ['AnthropicProvider'] },
          { path: 'src/providers/bedrock.ts', type: 'file', purpose: 'Stub — AWS Bedrock provider.', exports: ['BedrockProvider'] },
          { path: 'src/providers/azure-ai-foundry.ts', type: 'file', purpose: 'Stub — Azure AI Foundry provider.', exports: ['AzureAIFoundryProvider'] },
          { path: 'src/providers/langgraph-connector.ts', type: 'file', purpose: 'Stub — LangGraph Connectors provider.', exports: ['LangGraphConnectorProvider'] },
        ],
      },
      {
        path: 'src/scan/',
        type: 'dir',
        purpose: 'Scan pipeline engine — the core orchestration layer. Implements a 6-node LangGraph pipeline: clone → discover → deep_scan → cross_file → aggregate → persist. The worker claims jobs from a PostgreSQL queue (Job model), runs each node sequentially, and handles retries with exponential backoff. Each node reads from and writes to ScanState. Prompts are DB-backed (Config table) with hardcoded fallbacks.',
        children: [
          { path: 'src/scan/worker.ts', type: 'file', purpose: 'Main job loop — claims jobs, routes to nodes, manages scan lifecycle.', exports: ['processNextJob', 'startWorker', 'stopWorker'], dbTables: ['Job', 'Scan'] },
          { path: 'src/scan/queue.ts', type: 'file', purpose: 'Pipeline definition + job queue CRUD.', exports: ['NodeName', 'getPipeline', 'getNextNode', 'enqueueJob', 'claimNextJob', 'markJobComplete', 'markJobFailed', 'enqueuePipeline', 'enqueueNextJob', 'markScanCompletedIfNeeded', 'markScanFailed', 'cleanupStuckJobs'], dbTables: ['Job', 'Scan'] },
          { path: 'src/scan/state.ts', type: 'file', purpose: 'ScanState interface flowing through pipeline.', exports: ['ScanState', 'PrioritizedFile', 'ScanStatus'] },
          { path: 'src/scan/log.ts', type: 'file', purpose: 'Structured scan log persistence + retrieval.', exports: ['LogLevel', 'log', 'getLogs'], dbTables: ['ScanLog'] },
          { path: 'src/scan/cleanup.ts', type: 'file', purpose: 'Mark stuck scans/jobs as FAILED.', exports: ['cleanupStuckScans'], dbTables: ['Scan', 'Job'] },
          { path: 'src/scan/graph.ts', type: 'file', purpose: 'LangGraph StateGraph wiring 6 pipeline nodes.', exports: ['ScanStateAnnotation', 'createScanGraph'] },
          {
            path: 'src/scan/nodes/',
            type: 'dir',
            purpose: 'Pipeline node implementations — each file is one pipeline stage. clone (git clone --depth 1), discover (walk repo, filter by extension, assign security priority), deep-scan (per-file AI vulnerability analysis with batching + retry, DB-backed prompts), cross-file (aggregate file summaries into cross-cutting business logic rules), aggregate (deduplicate findings, filter by severity), persist (upsert findings, create triage tasks, save rules, mark scan complete).',
            children: [
              { path: 'src/scan/nodes/clone.ts', type: 'file', purpose: 'Git clone --depth 1 + extract commit SHA.', exports: ['cloneNode'] },
              { path: 'src/scan/nodes/discover.ts', type: 'file', purpose: 'Walk repo, filter by extension, assign security priority.', exports: ['discoverNode'] },
              { path: 'src/scan/nodes/deep-scan.ts', type: 'file', purpose: 'Per-file AI vulnerability analysis with batching, retries, singleFile rescan. Loads prompts from DB.', exports: ['deepScanNode'], dbTables: ['NodeOutput'] },
              { path: 'src/scan/nodes/cross-file.ts', type: 'file', purpose: 'Cross-file business logic inference from file summaries. Loads prompts from DB.', exports: ['crossFileNode'], dbTables: ['NodeOutput'] },
              { path: 'src/scan/nodes/aggregate.ts', type: 'file', purpose: 'Merge + deduplicate findings, filter by severity allowlist.', exports: ['aggregateNode'] },
              { path: 'src/scan/nodes/persist.ts', type: 'file', purpose: 'Write findings (upsert), create tasks, save rules, update scan.', exports: ['persistNode'], dbTables: ['Finding', 'BusinessLogicRule', 'Scan', 'Task'] },
            ],
          },
          {
            path: 'src/scan/prompts/',
            type: 'dir',
            purpose: 'AI prompt builders — constructs the system prompts sent to AI models during scanning. All 3 prompts (discover, deep-scan, cross-file) are exported as both hardcoded defaults and async DB loaders. The discover prompt includes file extension security priorities; deep-scan prompt includes vulnerability categories with explicit enum constraints; cross-file prompt builds a codebase map from file summaries.',
            children: [
              { path: 'src/scan/prompts/deep-scan.ts', type: 'file', purpose: 'Build discover/deep-scan/cross-file prompts with enum constraints. Exports defaults + async loadPrompts() from DB.', exports: ['DEFAULT_DISCOVER_PROMPT', 'DEFAULT_DEEP_SCAN_PROMPT', 'DEFAULT_CROSS_FILE_PROMPT', 'buildDiscoverPrompt', 'buildDeepScanPrompt', 'buildCrossFilePrompt', 'loadPrompts'] },
              { path: 'src/scan/prompts/cross-file.ts', type: 'file', purpose: 'Re-exports buildCrossFilePrompt from deep-scan.ts.', exports: ['buildCrossFilePrompt'] },
              { path: 'src/scan/prompts/discover.ts', type: 'file', purpose: 'Re-exports all 3 prompt builders from deep-scan.ts.', exports: ['buildDiscoverPrompt', 'buildDeepScanPrompt', 'buildCrossFilePrompt'] },
            ],
          },
          {
            path: 'src/scan/tools/',
            type: 'dir',
            purpose: 'LangChain tools for AI agent — these give the deep-scan AI agent read-only access to the target repo during scanning. File reader (with path-traversal protection and line-range support), directory lister (extension filter), code searcher (regex grep), and pattern matcher (7 built-in vulnerability pattern checks like SQL injection, hardcoded secrets, etc).',
            children: [
              { path: 'src/scan/tools/file-reader.ts', type: 'file', purpose: 'Read file contents with line-range + path-traversal protection.', exports: ['createFileReaderTool'] },
              { path: 'src/scan/tools/directory-lister.ts', type: 'file', purpose: 'List directory tree with extension filter.', exports: ['createDirectoryListerTool'] },
              { path: 'src/scan/tools/code-searcher.ts', type: 'file', purpose: 'Regex search across repo files.', exports: ['createCodeSearcherTool'] },
              { path: 'src/scan/tools/pattern-matcher.ts', type: 'file', purpose: '7 built-in vulnerability pattern checks.', exports: ['createPatternMatcherTool'] },
              { path: 'src/scan/tools/index.ts', type: 'file', purpose: 'Barrel re-export of all 4 tools.' },
            ],
          },
          {
            path: 'src/scan/reports/',
            type: 'dir',
            purpose: 'Report generators — export scan results as self-contained HTML (dark-themed, all CSS inline) or Markdown (tables + finding sections). Both generate from the same ReportData interface.',
            children: [
              { path: 'src/scan/reports/types.ts', type: 'file', purpose: 'ReportData interface.', exports: ['ReportData'] },
              { path: 'src/scan/reports/html.ts', type: 'file', purpose: 'Self-contained dark-themed HTML report.', exports: ['generateReportHtml'] },
              { path: 'src/scan/reports/markdown.ts', type: 'file', purpose: 'Markdown report with tables + finding sections.', exports: ['generateReportMarkdown'] },
            ],
          },
        ],
      },
      {
        path: 'src/findings/',
        type: 'dir',
        purpose: 'Finding aggregation and deduplication — the post-scan processing layer. Types define the UnifiedFinding schema (severity, category, fingerprint, CWE/OWASP, AI explanation/fix). The dedup module computes SHA-256 fingerprints from scanner+ruleId+file+line to eliminate duplicates across scanners. The aggregator flattens multi-scanner results and keeps the highest severity on collision.',
        children: [
          { path: 'src/findings/types.ts', type: 'file', purpose: 'Core types: Severity, Category, UnifiedFinding, BusinessLogicRule, FileSummary.', exports: ['Severity', 'Category', 'UnifiedFinding', 'BusinessLogicRule', 'FileSummary'] },
          { path: 'src/findings/dedup.ts', type: 'file', purpose: 'SHA-256 fingerprinting + duplicate check.', exports: ['fingerprint', 'isDuplicate'] },
          { path: 'src/findings/aggregator.ts', type: 'file', purpose: 'Flatten + deduplicate finding arrays, keep highest severity on collision.', exports: ['aggregate'] },
        ],
      },
      {
        path: 'src/rules/',
        type: 'dir',
        purpose: 'Custom rule DSL loader and parser — defines a .rule file format that lets users write custom scanning rules. The parser converts rule text to structured ParsedRule objects; the loader reads rule files from the rules/ directory and assembles a KnowledgeBase containing rules and prompt overrides.',
        children: [
          { path: 'src/rules/parser.ts', type: 'file', purpose: 'Parse .rule DSL into structured objects.', exports: ['ParsedRule', 'parseScanRule', 'ruleToContext'] },
          { path: 'src/rules/loader.ts', type: 'file', purpose: 'Load rule files from rules/ directory + prompt overrides.', exports: ['KnowledgeBase', 'loadKnowledgeBase'] },
        ],
      },
      {
        path: 'src/generated/prisma/',
        type: 'dir',
        purpose: 'Auto-generated Prisma client and model types — created by prisma generate. Contains the full TypeScript type definitions for all 16 database models: AiCallLog, AiConversation, AlertComment, AlertHistory, BusinessLogicRule, Config, Finding, GithubProfile, Job, NodeOutput, Preset, Scan, ScanLog, Task, TaskComment, TaskHistory, User, UserPreference, UserRule. Do not edit manually — regenerate after schema changes.',
        children: [
          { path: 'src/generated/prisma/', type: 'file', purpose: 'Auto-generated by Prisma. Models: AiCallLog, AiConversation, AlertComment, AlertHistory, BusinessLogicRule, Config, Finding, GithubProfile, Job, NodeOutput, Preset, Scan, ScanLog, Task, TaskComment, TaskHistory, User, UserPreference, UserRule.' },
        ],
      },
    ],
  },
];